steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './build/package/Dockerfile.firebase', '-t', 'gcr.io/$PROJECT_ID/firebase', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/firebase']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './build/package/Dockerfile.neoshogi', '-t', 'gcr.io/$PROJECT_ID/neoshogi', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/neoshogi']
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      gcloud beta run deploy neoshogi \
      --image gcr.io/$PROJECT_ID/neoshogi \
      --region asia-northeast1 \
      --platform managed \
      --allow-unauthenticated \
      --quiet
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: [ 'deploy', '--only', 'hosting:neoshogi']
  secretEnv: ['FIREBASE_TOKEN']
images:
- 'gcr.io/$PROJECT_ID/neoshogi'
- 'gcr.io/$PROJECT_ID/firebase'
secrets:
- kmsKeyName: projects/doi-t-alpha/locations/global/keyRings/neoshogi/cryptoKeys/firebase-token
  secretEnv:
    FIREBASE_TOKEN: CiQAfXuhstN4Y7o8UB2Jskzy+l1aZY/4ftfFk/d0MYLAE+P1ODQSVgAsLWaAnNk/SChgJM7GUKbuvT3LRfsQirHCbZ9BXfd8p/wwHbY9cSDi/fZW3umN6Zs/73BodHHGD4rONWDVVeJZYDoH7SgYQefS9Dn4zUV6OdmPXmco
