export default Object.freeze({
  GAME_TURN_BLACK: "black",
  GAME_TURN_WHITE: "white",
  GAME_STATUS_INIT: "initGame",
  GAME_STATUS_DEPLOYING: "deploying",
  GAME_STATUS_PLAYING: "playing",
  GAME_STATUS_END: "endGame",
  // Initial unit arrangement and move powers
  // role: "", "unit" or "king"
  // moves: upLeft, up, upRight, left, center, right, downLeft, down, downRight
  // e.g. moves: [0, 1, 0, 0, "*", 0, 0, 0, 0];
  UPLEFT: 0,
  UP: 1,
  UPRIGHT: 2,
  LEFT: 3,
  CENTER: 4,
  RIGHT: 5,
  DOWNLEFT: 6,
  DOWN: 7,
  DOWNRIGHT: 8,
  gamePresets: {
    "3": {
      deploymentArea: 2,
      units: [
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "unit", moves: [4, 4, 4, 4, "*", 3, 3, 3, 3] },
        { role: "king", moves: [1, 1, 1, 1, "*", 1, 1, 1, 1] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] }
      ]
    },
    "5": {
      deploymentArea: 3,
      units: [
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [3, 4, 2, 1, "*", 4, 2, 3, 1] },
        { role: "unit", moves: [10, 10, 10, 10, "*", 10, 10, 10, 10] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "", moves: [] },
        { role: "unit", moves: [1, 1, 1, 1, "*", 1, 0, 1, 0] },
        { role: "king", moves: [1, 1, 1, 1, "*", 1, 1, 1, 1] },
        { role: "unit", moves: [1, 1, 1, 1, "*", 1, 0, 1, 0] },
        { role: "", moves: [] }
      ]
    },
    "7": {
      deploymentArea: 4,
      units: [
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "unit", moves: [3, 4, 2, 1, "*", 4, 2, 3, 1] },
        { role: "king", moves: [10, 10, 10, 10, "*", 10, 10, 10, 10] },
        { role: "king", moves: [5, 4, 3, 2, "*", 2, 4, 5, 3] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "unit", moves: [1, 0, 1, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [1, 1, 1, 0, "*", 0, 1, 0, 1] },
        { role: "unit", moves: [1, 1, 1, 1, "*", 1, 0, 1, 0] },
        { role: "king", moves: [1, 1, 1, 1, "*", 1, 1, 1, 1] },
        { role: "unit", moves: [1, 1, 1, 1, "*", 1, 0, 1, 0] },
        { role: "unit", moves: [1, 1, 1, 0, "*", 0, 1, 0, 1] },
        { role: "unit", moves: [1, 0, 1, 0, "*", 0, 0, 0, 0] }
      ]
    },
    "9": {
      deploymentArea: 6,
      units: [
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 1, 0, 0, "*", 0, 0, 0, 0] },
        { role: "", moves: [] },
        { role: "unit", moves: [10, 0, 10, 0, "*", 0, 10, 0, 10] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "", moves: [] },
        { role: "unit", moves: [0, 10, 0, 10, "*", 10, 0, 10, 0] },
        { role: "", moves: [] },
        { role: "unit", moves: [0, 10, 0, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [1, 0, 1, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [1, 1, 1, 0, "*", 0, 1, 0, 1] },
        { role: "unit", moves: [1, 1, 1, 1, "*", 1, 0, 1, 0] },
        { role: "king", moves: [1, 1, 1, 1, "*", 1, 1, 1, 1] },
        { role: "unit", moves: [1, 1, 1, 1, "*", 1, 0, 1, 0] },
        { role: "unit", moves: [1, 1, 1, 0, "*", 0, 1, 0, 1] },
        { role: "unit", moves: [1, 0, 1, 0, "*", 0, 0, 0, 0] },
        { role: "unit", moves: [0, 10, 0, 0, "*", 0, 0, 0, 0] }
      ]
    }
  }
});
